server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: main-service-route
            uri: lb://MAIN-SERVICE
            predicates:
              - Path=/main/**

          - id: auth-service-route
            uri: lb://AUTH-SERVICE
            predicates:
              - Path=/auth/**

          - id: usage-service-route
            uri: lb://USAGE-SERVICE
            predicates:
              - Path=/usage/**


    openfeign:
      micrometer:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans


jwt:
  secret: YOUR_JWT_SECRET_KEY
  expirationTime: 1500000
