server:
  port: 8090

spring:
  application:
    name: email-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: notification.ashwinsi@gmail.com
    password: kobukhojpvpgahhy

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cloud:
    openfeign:
      micrometer:
        enabled: true

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/